SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[INSERT_STG_RESTRUCTURE_ALLSOURCE]
AS

BEGIN

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/

TRUNCATE TABLE ALL_SOURCE_STG_RESTRUCTURE



/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

--SELECT * INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_RESTRUCTURE  FROM ALL_SOURCE_STG_RESTRUCTURE WHERE 1=2
--DROP TABLE ALL_SOURCE_STG_RESTRUCTURE
INSERT INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_RESTRUCTURE (AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCH_ID,	TEN_PC_DATE)

SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCH_ID,	TEN_PC_DATE FROM Ecbf_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCHID,	TEN_PC_DATE FROM FINACLE_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCHID,	TEN_PC_DATE FROM GANASEVA_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCH_ID,	TEN_PC_DATE FROM Prolendz_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCH_ID,	TEN_PC_DATE FROM PTSMART_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCHID,	TEN_PC_DATE FROM Securitize_Stg_Restructure
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	RESTR_DATE,	RESTR_TYPE,	RESTR_AMT,	DFV_AMT,	TKOUT_FIN,	LATEST_REPAY_DATE,	BATCH_ID,	TEN_PC_DATE FROM VisionPlus_Stg_Restructure


END
GO