SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INSERT_STD_PROVISION_ALL_SOURCE_SYSTEM]
AS
BEGIN

--SELECT * INTO STD_PROVISION_ALL_SOURCE_SYSTEM FROM MERGE_STD_PROVISION

/*INSERT IN STD_PROVISION_ALL_SOURCE_SYSTEM FROM  MERGE_STD_PROVISION*/

INSERT INTO STD_PROVISION_ALL_SOURCE_SYSTEM(
										AS_ON_DATE
										,SOURCE
										,ENT_CIF
										,SRC_CIF
										,ACC_NO
										,STD_ASSET_CAT
									)
		SELECT 
			AS_ON_DATE
			,SOURCE
			,ENT_CIF
			,SRC_CIF
			,ACC_NO
			,STD_ASSET_CAT
		FROM MERGE_STD_PROVISION

END
GO