SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[INSERT_STG_COBORROWER_ALLSOURCE]
AS

BEGIN

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/

TRUNCATE TABLE IBL_ENPA_STGDB_V2.DBO.MERGE_COBORROWER

/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

--SELECT * INTO MERGE_COBORROWER FROM ALL_SOURCE_STG_COBORROWER WHERE 1=2

INSERT INTO IBL_ENPA_STGDB_V2.DBO.MERGE_COBORROWER (AS_ON_DATE,	ENT_CIF,	SOURCE,	SRC_CIF,	ACC_NO,	COBO_ENT_CIF)

SELECT AS_ON_DATE,	ENT_CIF,	SOURCE,	SRC_CIF,	ACC_NO,	COBO_ENT_CIF FROM Finacle_coborrower_stg_daily
UNION ALL
SELECT AS_ON_DATE,	ENT_CIF,	SOURCE,	SRC_CIF,	ACC_NO,	ENT_CIF_COBORR FROM Prolendz_Stg_coborrower
UNION ALL
SELECT Asondate,	NCIFID_primaryaccount,	SourceSystemName_primaryaccount,	CustomerID_primaryaccount,	CustomerAcID_primaryaccount,	NCIFID_COBORROWER FROM PTSmart_Stg_Coborrower
UNION ALL
SELECT AS_ON_DATE,	ENT_CIF,	SOURCE,	SRC_CIF,	ACC_NO,	COBO_ENT_CIF FROM Securitize_stg_coborrower


END
GO