SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[INSERT_STG_SECURITY_ALLSOURCE]
AS

BEGIN

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/

TRUNCATE TABLE [IBL_ENPA_STGDB_V2].DBO.MERGE_SECURITY

--SELECT * INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_SECURITY FROM [IBL_ENPA_STGDB_V2].DBO.ALL_SOURCE_STG_SECURITY
--DROP TABLE [IBL_ENPA_STGDB_V2].DBO.ALL_SOURCE_STG_SECURITY

/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

--SELECT * INTO ALL_SOURCE_STG_SECURITY FROM Ecbf_Stg_Security WHERE 1=2

INSERT INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_SECURITY (AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCH_ID,	COLL_DELINK_DATE)

SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCH_ID,	COLL_DELINK_DATE FROM Ecbf_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCHID,	COLL_DELINK_DATE FROM FINACLE_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCHID,	COLL_DELINK_DATE FROM GANASEVA_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCH_ID,	COLL_DELINK_DATE FROM Prolendz_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCH_ID,	COLL_DELINK_DATE FROM PTSMART_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCHID,	COLL_DELINK_DATE FROM Securitize_Stg_Security
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	COLL_ID,	ENT_CIF,	SRC_CIF,	COLL_TYPE,	COLL_EXPRY_DATE,	COLL_AMT,	ACC_NO,	COLL_VAL_DATE,	BATCH_ID,	COLL_DELINK_DATE FROM VisionPlus_Stg_Security


END
GO