SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[INSERT_STG_INCREMENTAL_ALLSOURCE]
AS

BEGIN

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/

TRUNCATE TABLE [IBL_ENPA_STGDB_V2].DBO.CUSTAC_MERGE_INCREMENTAL

/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

--SELECT * INTO ALL_SOURCE_STG_INCREMENTAL FROM Calypso_Stg_Incremental WHERE 1=2


--SELECT * INTO CUSTAC_MERGE_INCREMENTAL FROM ALL_SOURCE_STG_INCREMENTAL WHERE 1=2
--DROP TABLE ALL_SOURCE_STG_INCREMENTAL




INSERT INTO [IBL_ENPA_STGDB_V2].DBO.CUSTAC_MERGE_INCREMENTAL (AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING)
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Calypso_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Ecbf_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCHID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM FINACLE_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCHID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Ganaseva_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCHID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM M2P_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Prolendz_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM PTSmart_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCHID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Securitize_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Tradepro_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	NULL,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM Veefin_Stg_Incremental
UNION ALL
SELECT AsOnDate,	SourceName,	UCIF_ID,	RefCustomerID,	CustomerAcID,	SrcAssetClass,	BranchCode,	SrcNpaDt,	CustName,	FacilityType,	ProductCode,	ProductName,	PAN,	SancLimit,	SancDate,	Region,	State,	Zone,	NPA_TagDate,	Sector,	PS_NPS,	Retail_Corpo,	Area,	ActSegmentCode,	FraudAmt,	FraudDate,	GovGtyAmt,	GtyRepudiated,	RepudiationDate,	OTS_Amt,	TWO_Date,	TWO_Amt,	ARC_SaleDate,	ARC_SaleAmt,	PrincOverdueSinceDt,	IntNotServicedDt,	ContiExcessDt,	ReviewDueDt,	OtherOverdueSinceDt,	IntOverdueSinceDt,	SecuredFlag,	StkStmtDate,	IsRestructured,	IsOTS,	IsTWO,	IsARC_Sale,	IsFraud,	IsWiful,	IsNonCooperative,	IsSuitFiled,	IsRFA,	IsFITL,	IsCentral_GovGty,	Is_Oth_GovGty,	CLOSED_DATE,	BATCH_ID,	Funded_NonFunded_Flag,	SRC_CIF_UPDATED,	DCCO_Date,	PROJ_COMPLETION_DATE,	OPEN_DATE,	NATUREOFCLASSIFICATION,	DATEOFIMPACTING FROM VisionPlus_Stg_Incremental


END
GO