SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[UpdateAutomate_Advances]
as 
begin

UPDATE RBL_STGDB.DBO.AUTOMATE_ADVANCES SET EXT_FLG='N' Where EXT_FLG='Y'
UPDATE RBL_MISDB.DBO.AUTOMATE_ADVANCES SET EXT_FLG='N' Where EXT_FLG='Y'
UPDATE RBL_MISDB.DBO.EXT_DATE_MISDB SET EXTFLAG='U' WHERE   EXTFLAG='Y'
UPDATE RBL_MISDB.DBO.SYSDATAMATRIX SET CURRENTSTATUS='U' WHERE   CURRENTSTATUS='C'
UPDATE RBL_MISDB.DBO.EXT_DATE_MISDB  SET EXTFLAG='Y' WHERE EXTDATE IN (SELECT CAST(GETDATE()-1 AS DATE))-------EXTRATION DATE
UPDATE RBL_MISDB.DBO.SYSDATAMATRIX SET CURRENTSTATUS='C' FROM RBL_MISDB.DBO.SYSDATAMATRIX  INNER JOIN RBL_MISDB.DBO.EXT_DATE_MISDB 
ON RBL_MISDB.DBO.SYSDATAMATRIX .TIMEKEY=RBL_MISDB.DBO.EXT_DATE_MISDB.TIMEKEY WHERE    EXTFLAG='Y' -------EXTRATION DATE

  UPDATE RBL_STGDB.DBO.AUTOMATE_ADVANCES  SET EXT_FLG='Y' FROM RBL_STGDB.DBO.AUTOMATE_ADVANCES 
  INNER JOIN  RBL_MISDB.DBO.EXT_DATE_MISDB ON RBL_STGDB.DBO.AUTOMATE_ADVANCES.Timekey=RBL_MISDB.DBO.EXT_DATE_MISDB.Timekey 
  WHERE   EXTFLAG='Y' 

  UPDATE RBL_MISDB.DBO.AUTOMATE_ADVANCES  SET EXT_FLG='Y' FROM RBL_MISDB.DBO.AUTOMATE_ADVANCES 
  INNER JOIN  RBL_MISDB.DBO.EXT_DATE_MISDB ON RBL_MISDB.DBO.AUTOMATE_ADVANCES.Timekey=RBL_MISDB.DBO.EXT_DATE_MISDB.Timekey 
  WHERE   EXTFLAG='Y' 
  END

GO