SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[INSERT_STG_PROVISION_ALLSOURCE]
AS

BEGIN

/*ALTERED SCRIPT ON LOCAL REMOVING UNWANTED COLUMN FROM STG WHICH WAS CREATED INCORRECTLY*/
/*
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN TOTAL_OS
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN PRINCIPAL_OUTSTANDING
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN INT_OVDU
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN INTEREST_ACCRUED
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN OTHER_OVERDUE
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN PRINC_OVDU
ALTER TABLE Finacle_Provision_stg_daily DROP COLUMN BATCH_ID

ALTER TABLE Prolendz_Provision_Stg_Daily DROP COLUMN GENERATION_TIMESTAMP
ALTER TABLE Prolendz_Provision_Stg_Daily DROP COLUMN BATCH_ID
ALTER TABLE Prolendz_Provision_Stg_Daily DROP COLUMN SOURCE_DATA


ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN TOT_OS
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN PRIN_OS
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN INT_UNSRVCD
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN INT_ACC
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN OTHR_OVRDUE
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN PRIN_OVRDUE
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN BATCH_ID
ALTER TABLE PTSMART_Provision_Stg_Daily DROP COLUMN Generation_Timestamp
*/

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/


TRUNCATE TABLE [IBL_ENPA_STGDB_V2].DBO.MERGE_STD_PROVISION

/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

--SELECT * INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_STD_PROVISION FROM ALL_SOURCE_STG_PROVISION WHERE 1=2

INSERT INTO [IBL_ENPA_STGDB_V2].DBO.MERGE_STD_PROVISION (AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT)

SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM Finacle_Provision_stg_daily
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM Ganaseva_Provision_Stg_Daily
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM Prolendz_Provision_Stg_Daily
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM PTSMART_Provision_Stg_Daily
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM Securitize_Stg_Provision
UNION ALL
SELECT AS_ON_DATE,	SOURCE,	ENT_CIF,	SRC_CIF,	ACC_NO,	STD_ASSET_CAT FROM VisionPlus_Provision_Stg_Daily


END
GO