CREATE TABLE [dbo].[ACCOUNT_ALL_SOURCE_SYSTEM_BKP_20250407] (
  [DateofData] [date] NULL,
  [SourceSystem] [varchar](30) NULL,
  [BranchCode] [varchar](10) NULL,
  [UCIC_ID] [varchar](20) NULL,
  [CustomerID] [varchar](30) NULL,
  [CustomerAcID] [varchar](30) NULL,
  [AcOpenDt] [date] NULL,
  [SchemeType] [varchar](30) NULL,
  [Scheme_ProductCode] [varchar](30) NULL,
  [AcSegmentCode] [varchar](30) NULL,
  [FacilityType] [varchar](10) NULL,
  [GLCode] [varchar](30) NULL,
  [Sector] [varchar](50) NULL,
  [PurposeofAdvance] [varchar](100) NULL,
  [IndustryCode] [varchar](10) NULL,
  [FirstDtOfDisb] [date] NULL,
  [InttRate] [decimal](4, 2) NULL,
  [BankingArrangement] [varchar](50) NULL,
  [CurrencyCode] [varchar](10) NULL,
  [UnhedgedFCYAmount] [decimal](16, 2) NULL,
  [BalanceOutstandingINR] [decimal](16, 2) NULL,
  [BalanceInActualAcCurrency] [decimal](16, 2) NULL,
  [AdvanceRecoveryAmount] [decimal](16, 2) NULL,
  [CurQtrCredit] [decimal](16, 2) NULL,
  [CurQtrInt] [decimal](16, 2) NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [CurrentLimitDate] [date] NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [AdhocAmt] [decimal](16, 2) NULL,
  [AdhocDate] [date] NULL,
  [AdhocExpiryDate] [date] NULL,
  [ContiExcessDate] [date] NULL,
  [DebitSinceDate] [date] NULL,
  [DFVAmt] [decimal](16, 2) NULL,
  [GovtGtyAmt] [decimal](16, 2) NULL,
  [IntNotServicedDate] [date] NULL,
  [LastCreditDate] [date] NULL,
  [POSBalance] [decimal](16, 2) NULL,
  [PrincipalOverdueAmt] [decimal](16, 2) NULL,
  [PrincipalOverDueSinceDt] [date] NULL,
  [InterestOverdueAmt] [decimal](16, 2) NULL,
  [InterestOverDueSinceDt] [date] NULL,
  [OthChargesOverdueAmt] [decimal](16, 2) NULL,
  [OthChangesOverDueSinceDt] [date] NULL,
  [Review_RenewDueDt] [date] NULL,
  [LimitExpiryDate] [date] NULL,
  [StockStatementDt] [date] NULL,
  [UnAppliedInterestAmt] [decimal](16, 2) NULL,
  [TWODate] [date] NULL,
  [TWOAmount] [decimal](16, 2) NULL,
  [AssetClassNorm] [varchar](10) NULL,
  [ACCategory] [tinyint] NULL,
  [SecuredStatus] [varchar](20) NULL,
  [AssetClassCode] [varchar](15) NULL,
  [NPADate] [date] NULL,
  [DBT_LOSDate] [date] NULL,
  [STDProvisionCategory] [varchar](20) NULL,
  [FraudCommitted] [varchar](20) NULL,
  [FraudDate] [date] NULL,
  [IsIBPCExposure] [varchar](20) NULL,
  [IsSecurtisedExposure] [varchar](20) NULL,
  [AcRMName_ID] [varchar](50) NULL,
  [AcTLName_ID] [varchar](50) NULL,
  [PUIMarked] [varchar](20) NULL,
  [RFAMarked] [varchar](20) NULL,
  [IsNonCoperative] [varchar](20) NULL,
  [CurrQtrSecurityValue] [decimal](16) NULL,
  [PrvQtrSecurityValue] [decimal](16) NULL,
  [CorporateUCICID] [varchar](20) NULL,
  [CorporateCustomerID] [varchar](20) NULL,
  [Liability] [varchar](20) NULL,
  [CD] [int] NULL,
  [Bucket] [varchar](20) NULL,
  [Accountstatus] [varchar](20) NULL,
  [AccountBlkCode1] [varchar](20) NULL,
  [AccountBlkCode2] [varchar](20) NULL,
  [ChargeoffY_N] [char](1) NULL,
  [ChargeoffType] [varchar](20) NULL,
  [ChargeoffAmount] [decimal](16, 2) NULL,
  [ChargeoffDate] [date] NULL,
  [PrincipalOS] [decimal](16, 2) NULL,
  [InterestOs] [decimal](16, 2) NULL,
  [OtherChargesOS] [decimal](16, 2) NULL,
  [ST_GSTTaxOS] [decimal](16, 2) NULL,
  [interest_due] [decimal](18, 6) NULL,
  [other_dues] [decimal](18, 6) NULL,
  [penal_due] [decimal](18, 6) NULL,
  [int_receivable] [decimal](18, 6) NULL,
  [penal_int_receivable] [decimal](18, 6) NULL,
  [DPD] [int] NULL,
  [Accured_Interest] [decimal](16, 2) NULL,
  [Settlement_Flag] [varchar](1) NULL,
  [Settlement_Date] [date] NULL,
  [IsARC_Sale] [varchar](3) NULL,
  [IsWiful] [varchar](3) NULL,
  [IsSuitFiled] [varchar](3) NULL,
  [Funded_NonFunded_Flag] [varchar](3) NULL,
  [DCCO_Date] [date] NULL,
  [PROJ_COMPLETION_DATE] [date] NULL,
  [IsTWO] [varchar](1) NULL,
  [IsOTS] [varchar](1) NULL,
  [IsFITL] [varchar](1) NULL,
  [CLOSED_DATE] [date] NULL
)
ON [PRIMARY]
GO