CREATE TABLE [dbo].[TRADEPRO_Stg_Incremental_BKP_20250407] (
  [AsOnDate] [date] NULL,
  [SourceName] [varchar](30) NULL,
  [UCIF_ID] [varchar](20) NULL,
  [RefCustomerID] [varchar](20) NULL,
  [CustomerAcID] [varchar](20) NULL,
  [SrcAssetClass] [varchar](20) NULL,
  [BranchCode] [varchar](10) NULL,
  [SrcNpaDt] [date] NULL,
  [CustName] [varchar](100) NULL,
  [FacilityType] [varchar](10) NULL,
  [ProductCode] [varchar](10) NULL,
  [ProductName] [varchar](100) NULL,
  [PAN] [varchar](50) NULL,
  [SancLimit] [decimal](38, 2) NULL,
  [SancDate] [date] NULL,
  [Region] [varchar](20) NULL,
  [State] [varchar](50) NULL,
  [Zone] [varchar](50) NULL,
  [NPA_TagDate] [date] NULL,
  [Sector] [varchar](10) NULL,
  [PS_NPS] [varchar](50) NULL,
  [Retail_Corpo] [varchar](10) NULL,
  [Area] [varchar](10) NULL,
  [ActSegmentCode] [varchar](100) NULL,
  [FraudAmt] [decimal] NULL,
  [FraudDate] [date] NULL,
  [GovGtyAmt] [decimal] NULL,
  [GtyRepudiated] [varchar](1) NULL,
  [RepudiationDate] [date] NULL,
  [OTS_Amt] [decimal](38, 2) NULL,
  [TWO_Date] [date] NULL,
  [TWO_Amt] [decimal](16, 2) NULL,
  [ARC_SaleDate] [date] NULL,
  [ARC_SaleAmt] [decimal](16, 2) NULL,
  [PrincOverdueSinceDt] [date] NULL,
  [IntNotServicedDt] [date] NULL,
  [ContiExcessDt] [date] NULL,
  [ReviewDueDt] [date] NULL,
  [OtherOverdueSinceDt] [date] NULL,
  [IntOverdueSinceDt] [date] NULL,
  [SecuredFlag] [varchar](1) NULL,
  [StkStmtDate] [date] NULL,
  [IsRestructured] [varchar](1) NULL,
  [IsOTS] [varchar](1) NULL,
  [IsTWO] [varchar](1) NULL,
  [IsARC_Sale] [varchar](1) NULL,
  [IsFraud] [varchar](1) NULL,
  [IsWiful] [varchar](1) NULL,
  [IsNonCooperative] [varchar](1) NULL,
  [IsSuitFiled] [varchar](1) NULL,
  [IsRFA] [varchar](1) NULL,
  [IsFITL] [varchar](1) NULL,
  [IsCentral_GovGty] [varchar](1) NULL,
  [Is_Oth_GovGty] [varchar](1) NULL,
  [CLOSED_DATE] [date] NULL,
  [BATCH_ID] [varchar](100) NULL,
  [Funded_NonFunded_Flag] [char](1) NULL,
  [SRC_CIF_UPDATED] [char](1) NULL,
  [DCCO_Date] [date] NULL,
  [PROJ_COMPLETION_DATE] [date] NULL,
  [OPEN_DATE] [date] NULL,
  [NATUREOFCLASSIFICATION] [varchar](30) NULL,
  [DATEOFIMPACTING] [varchar](20) NULL
)
ON [PRIMARY]
GO